// new lines (count = 0):



// old lines (count = 4)

__d("XInstreamVideoSponsoredStoryAsyncController",["XController"],(function(t,n,r,o,a,i){a.exports=n("XController").create("/video/instream_video/view/story/async/",{host_video_id:{type:"FBID",required:!0},instream_video_type:{type:"Enum",required:!0,enumType:1},instream_video_break_index:{type:"Int",required:!0},player_origin:{type:"String"},player_sub_origin:{type:"String"},script_path:{type:"String"},video_channel_caller:{type:"Enum",enumType:1},is_sponsored_host_video:{type:"Bool",defaultValue:!1},referrer:{type:"String"},option_menu_button_id:{type:"String"},host_video_stall_count:{type:"Int"},ad_break_duration_ms:{type:"Int"},player_format:{type:"String"},instream_placement:{type:"Enum",required:!0,enumType:1},story_identifier:{type:"String"},window_href:{type:"String"},ad_trigger_source:{type:"Enum",enumType:1},client_live_video_timestamp:{type:"Int"}})}),null);
__d("XInstreamVideoSponsoredStoryAsyncController",["XController"],(function(t,n,r,o,a,i){a.exports=n("XController").create("/video/instream_video/view/story/async/",{host_video_id:{type:"FBID",required:!0},instream_video_type:{type:"Enum",required:!0,enumType:1},instream_video_break_index:{type:"Int",required:!0},player_origin:{type:"String"},player_sub_origin:{type:"String"},script_path:{type:"String"},video_channel_caller:{type:"Enum",enumType:1},is_sponsored_host_video:{type:"Bool",defaultValue:!1},referrer:{type:"String"},option_menu_button_id:{type:"String"},host_video_stall_count:{type:"Int"},ad_break_duration_ms:{type:"Int"},player_format:{type:"String"},instream_placement:{type:"Enum",required:!0,enumType:1},story_identifier:{type:"String"},window_href:{type:"String"},ad_trigger_source:{type:"Enum",enumType:1},client_live_video_timestamp:{type:"Int"}})}),null);
__d("XInstreamVideoSponsoredStoryAsyncController",["XController"],(function(t,n,r,o,a,i){a.exports=n("XController").create("/video/instream_video/view/story/async/",{host_video_id:{type:"FBID",required:!0},instream_video_type:{type:"Enum",required:!0,enumType:1},instream_video_break_index:{type:"Int",required:!0},player_origin:{type:"String"},player_sub_origin:{type:"String"},script_path:{type:"String"},video_channel_caller:{type:"Enum",enumType:1},is_sponsored_host_video:{type:"Bool",defaultValue:!1},referrer:{type:"String"},option_menu_button_id:{type:"String"},host_video_stall_count:{type:"Int"},ad_break_duration_ms:{type:"Int"},player_format:{type:"String"},instream_placement:{type:"Enum",required:!0,enumType:1},story_identifier:{type:"String"},window_href:{type:"String"},ad_trigger_source:{type:"Enum",enumType:1},client_live_video_timestamp:{type:"Int"}})}),null);
__d("XInstreamVideoSponsoredStoryAsyncController",["XController"],(function(t,n,r,o,a,i){a.exports=n("XController").create("/video/instream_video/view/story/async/",{host_video_id:{type:"FBID",required:!0},instream_video_type:{type:"Enum",required:!0,enumType:1},instream_video_break_index:{type:"Int",required:!0},player_origin:{type:"String"},player_sub_origin:{type:"String"},script_path:{type:"String"},video_channel_caller:{type:"Enum",enumType:1},is_sponsored_host_video:{type:"Bool",defaultValue:!1},referrer:{type:"String"},option_menu_button_id:{type:"String"},host_video_stall_count:{type:"Int"},ad_break_duration_ms:{type:"Int"},player_format:{type:"String"},instream_placement:{type:"Enum",required:!0,enumType:1},story_identifier:{type:"String"},window_href:{type:"String"},ad_trigger_source:{type:"Enum",enumType:1},client_live_video_timestamp:{type:"Int"}})}),null);